# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: selfhosted

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.BinariesDirectory)'
    includeRootFolder: true
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true

- script: |
    dir
  displayName: 'Artifacts Details'    

- task: AzureFileCopy@6
  inputs:
    SourcePath: 'C:\Users\ManikandanS\agent\_work\1\a\11.zip'
    azureSubscription: 'Microsoft Azure Sponsorship- Rapyder(438425ff-21cd-4300-90ba-3105f03ce85c)'
    Destination: 'AzureBlob'
    storage: 'tfrapyderpoc'
    ContainerName: 'servicecatalog'
    CleanTargetBeforeCopy: true

- task: PublishPipelineMetadata@0
